### ISSUE TITLE
python candle version not compatible 

### ISSUE THREAD

**Issue by LarkinLabs** [mabrobotics/candle#18]
[CANDLE] MD80's firmware with ID: 200 is a future version. Please update your CANdle library.  [FAILED]

**Comment by klonyyy** [comment]
Hello, 
Please use the instructions form the Downloads page and the [devel section note](https://mabrobotics.github.io/MD80-x-CANdle-Documentation/Downloads/Downloads.html#software-devel). This should resolve the problem.
