### ISSUE TITLE
motor configs not uploading 

### ISSUE THREAD

**Issue by LarkinLabs** [mabrobotics/candle#19]
Motor config parameter in category [limits] named [max velocity] is out of bounds!
none of the examples have this 

what we are trying to upload.
[scrubber.txt](https://github.com/mabrobotics/candle/files/13667681/scrubber.txt)

readout from controller.
[MD80 config.txt](https://github.com/mabrobotics/candle/files/13667701/MD80.config.txt)

**Comment by LarkinLabs** [comment]
got it to accept the config file but still have a setup error current config file is:
[Uploading scrubberv2.txt…]()

**Comment by klonyyy** [comment]
Hello I'm unable to read the second file. Could you resend it? Also please use default [configs from the mdtool ](https://github.com/mabrobotics/mdtool/tree/devel/template_package/etc/mdtool/mdtool_motors) as a reference (from the devel branch).

**Comment by LarkinLabs** [comment]
I will have to send the file again when when im at work tomorrow.

I am using the the latest version.

We get a setup error and ask to resend the config.

We added every option from the config documentation

**Comment by LarkinLabs** [comment]
[scrubberv2.txt](https://github.com/mabrobotics/candle/files/13679036/scrubberv2.txt)

**Comment by klonyyy** [comment]
Could you also send me the "mdtool setup info <ID>" command output?

**Comment by PawelKorsak** [comment]
Inactive thread, closing
