### ISSUE TITLE
How to open a specific candle

### ISSUE THREAD

**Issue by pathammer** [mabrobotics/candle#22]
I see in example9 you can open multiple USB candles but how do you suggest opening a specific candle? Would this make sense:
```
def open_specific_candle(candle_id):
    candles = []
    to_return = None
    try:
        while True:
            candle = pyCandle.Candle()
            if candle.getDeviceId() == candle_id:
                to_return = candle
                break
            candles.append(candle)  # keep devices open
    except Exception:
        pass  # ran out of candles to open
    del candles  # close other devices
    return to_return
  ```

**Comment by klonyyy** [comment]
Sure, that should work, except you should pass the required arguments to Candle constructor: 

`def open_specific_candle(candle_id):
    candles = []
    to_return = None
    try:
        while True:
            candle = pyCandle.Candle(pyCandle.CAN_BAUD_1M, True)
            if candle.getDeviceId() == candle_id:
                to_return = candle
                break
            candles.append(candle)  # keep devices open
    except Exception:
        pass  # ran out of candles to open
    del candles  # close other devices
    return to_return`

I tried it and it seems to return the specified candle correctly.
